# Generated by Django 5.0.6 on 2024-07-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apaterno', models.CharField(max_length=20)),
                ('amaterno', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
    ]
