# Generated by Django 5.0.6 on 2024-07-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosdelmar', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=150),
        ),
    ]
