# Generated by Django 5.0.6 on 2024-07-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosdelmar', '0003_remove_producto_imagen_producto_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
