# Generated by Django 5.0.6 on 2024-07-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosdelmar', '0004_producto2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
